### ISSUE TITLE
关于在Hexo中使用本模型 Using the model on Hexo

### ISSUE THREAD

**Issue by Lemon-412** [akikowork/chtholly_kanban#1]
如果可以的话，请为如何在hexo博客中添加chtholly添加一个简明的教程，或指引一下其他教程，感激不尽！！

**Comment by Lemon-412** [comment]
例如我在[这里](https://github.com/EYHN/hexo-helper-live2d/blob/master/README.zh-CN.md)看到的教程，但蒟蒻并不知道如何配置……
```
# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  # enable: false
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    use: live2d-widget-model-wanko # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
```

**Comment by byronpiao** [comment]
阁下指引的链接中提到的教程已经十分清楚啦。
简而言之，是安装npm模块hexo-helper-live2d，在您Hexo博客的根目录下新建文件夹live2d_models，将本库的chtholly/assets文件夹拷贝到该文件夹下并改文件夹名为chtholly，在您Hexo的_config.yml中粘贴您复制的部分配置，注意修改model部分为：
```
model:
  use: chtholly
```
按上述操作应该可以在您的Hexo博客中实现模型使用噢。

**Comment by Lemon-412** [comment]
始终部署不上啊QAQ，我哭了……

在hexo主题_config.yml中加入以下内容：
```
live2d:
  enable: true
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: true # 调试, 是否在控制台输出日志
  model:
    use: chtholly
```

目前我站点根相关文件目录如下：
> ...
> live2d_models
>> chtholly
>>> chtholly.2048
>>> expressions
>>> motions
>>> chtholly.moc
>>> chtholly.model.json
>>> physics.json

得到控制台输出如下：
![image](https://user-images.githubusercontent.com/57213526/80938062-38ae8500-8e0a-11ea-8112-18c46ce86bc6.png)

两条报错源码依次如下：
![image](https://user-images.githubusercontent.com/57213526/80938220-e1f57b00-8e0a-11ea-9259-ba6b3fcc4a04.png)

![image](https://user-images.githubusercontent.com/57213526/80938300-25e88000-8e0b-11ea-8591-cf1df02c6b4c.png)

另外，我在博客各个站点已经看到了live2d的容器了，但是是透明的没有加载。是不是模型本身不兼容的关系呢？前端小白，虚心求教。

**Comment by WinHGGG** [comment]
非常抱歉，在调试wiki时在chtholly/assets/chtholly.model.json中加入了php语句，导致json解析出错。已修复。
